# Generated by Django 3.2.14 on 2022-07-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pull_users_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('t', 'transgender')], max_length=1),
        ),
    ]
