# Generated by Django 3.2.14 on 2022-07-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pull_users_api', '0004_alter_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='', max_length=1),
        ),
    ]
