# Generated by Django 3.2.14 on 2022-07-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pull_users_api', '0005_alter_users_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
